# Generated by Django 5.2.7 on 2025-11-09 00:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('duracao', models.CharField(blank=True, max_length=50, null=True)),
                ('modalidade', models.CharField(choices=[('Presencial', 'Presencial'), ('EAD', 'Educação a Distância'), ('Híbrido', 'Híbrido')], default='Presencial', help_text='Selecione a modalidade do curso', max_length=50)),
                ('habilitacao', models.CharField(blank=True, help_text='Ex: Bacharelado, Licenciatura, Tecnólogo', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('matricula', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefone', models.CharField(blank=True, max_length=15, null=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.curso')),
            ],
        ),
    ]
