# Generated by Django 5.2.7 on 2025-11-08 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='modalidade',
            field=models.CharField(choices=[('Presencial', 'Presencial'), ('EAD', 'Educação a Distância (EAD)'), ('Híbrido', 'Híbrido')], default='Presencial', max_length=20),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.curso'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='descricao',
            field=models.TextField(default='Sem descrição'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='duracao',
            field=models.CharField(blank=True, help_text='Ex: 4 anos', max_length=50, null=True),
        ),
    ]
