# Generated by Django 5.2.7 on 2025-11-09 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='habilitacao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='modalidade',
            field=models.CharField(blank=True, choices=[('Presencial', 'Presencial'), ('EAD', 'EAD'), ('Híbrido', 'Híbrido')], max_length=50, null=True),
        ),
    ]
