# Generated by Django 5.2.7 on 2025-11-08 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_curso_modalidade_alter_aluno_curso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='habilitacao',
            field=models.CharField(blank=True, help_text='Ex: Bacharelado, Licenciatura, Tecnólogo', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='duracao',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='modalidade',
            field=models.CharField(choices=[('Presencial', 'Presencial'), ('EAD', 'Educação a Distância'), ('Híbrido', 'Híbrido')], default='Presencial', help_text='Selecione a modalidade do curso', max_length=50),
        ),
        migrations.AlterField(
            model_name='curso',
            name='nome',
            field=models.CharField(max_length=100),
        ),
    ]
