# Generated by Django 5.2.7 on 2025-11-08 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_aluno_criado_em_alter_aluno_curso_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('duracao', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
